name: Build ASP.NET Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'
        msbuild-architecture: "x64"

    - name: Install NuGet dependencies
      run: nuget restore ./UsperyDocPrint.sln

    - name: Build solution
      run: msbuild ./UsperyDocPrint.sln /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: |
          **/bin/Release/
